### ISSUE TITLE
Create real GitHub releases

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [yandex/handystats#18]
Hi,

It seems the last release that you created in GitHub is 1.11.3 in 2015, while in the  recent commits you mention releases 1.11.4, 1.11.5 and 1.11.6. Some people (like my company) prefer having a real git tag and a real official release tarball (like the ones generated by GitHub when you officially flag a commit as release) when they use open source software. Would you please create such an official release ?

Thanks,
Romain

**Comment by shindo** [comment]
Hi!

Thanks for the notice. I've added 1.11.4, 1.11.5 and 1.11.6 releases.
